---

- name: Daily Server Maintenance and Checks
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
  - name: install updates (Ubuntu/Debian)
    tags: always
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install updates (Fedora/RHEL)
    dnf:
      name: "*"
      state: latest
    when: ansible_distribution == "Fedora"

  tasks:
    - name: run journalctl command and store output
      ansible.builtin.command: journalctl -p 3 -xb
      register: journal_output
      changed_when: false

    - name: Display problematic logs for each host
      ansible.builtin.debug:
        msg: "Host: {{ ansible_hostname }}\nIP Address:  \n{{ inventory_hostname }}\nLogs: \n{{ journal_output.stdout }}"
      when: journal_output.stdout | length > 0

    - name: Add date header to files
      ansible.builtin.set_fact:
        current_datetime: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
      run_once: true
      delegate_to: localhost

    - name: Create a file with hostname and logs on Ansible Control Node
      ansible.builtin.copy:
        dest:  "/home/blue-user/ansible-reports/problem_logs_report_{{ current_datetime }}_{{ inventory_hostname }}.tmp"
        content: |
          ==================================================
          HOST:     {{ ansible_hostname }}
          IP ADDR:  {{ inventory_hostname }}
          DATE:     {{ current_datetime }}
          ==================================================
          {{ journal_output.stdout }}

      delegate_to: localhost
      become: false

    - name: Remove old final reports if they exist
      ansible.builtin.file:
        path: "/home/blue-user/ansible-reports/final_problem_logs_report_{{ current_datetime }}.txt"
        state: absent
      delegate_to: localhost
      run_once: true
      become: false

    - name: Assemble all temporary log files into a final report
      ansible.builtin.assemble:
        src: "/home/blue-user/ansible-reports/"
        dest: "/home/blue-user/ansible-reports/final_problem_logs_report_{{ current_datetime }}.txt"
        regexp: 'problem_logs_report_{{ current_datetime}}_.*\.tmp$'
        remote_src: true
      delegate_to: localhost
      run_once: true
      become: false

    - name: Clean up temporary files
      ansible.builtin.file:
        path: "/home/blue-user/ansible-reports/problem_logs_report_{{ current_datetime }}_{{ inventory_hostname }}.tmp"
        state: absent
      delegate_to: localhost
      become: false

    - name: Check if system reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Notify if reboot required
      ansible.builtin.debug:
        msg: "\u001b[1;31m REBOOT REQUIRED: The file /var/run/reboot-required exists.\u001b[0m"
      when: reboot_required_file.stat.exists

    - name: Create reboot notification file for Jenkins
      ansible.builtin.copy:
        content: |
          The following hosts require a reboot:
          {% for host in ansible_play_hosts %}
          {% if hostvars[host].reboot_required_file.stat.exists %}
            - {{ hostvars[host].ansible_hostname }} ({{ host }})
          {% endfor %}
        dest: "/tmp/reboot_notification_{{ current_datetime }}.txt"
      delegate_to: localhost
      run_once: true
      become: false
      when: ansible_play_hosts | map('extract', hostvars) | selectattr('reboot_required_file.stat.exists') | list | length >0
