##  This Docker setup file was created for Debian

---

- name: Install Docker on Debian
  hosts: db-servers
  become: yes

  vars:
    docker_group_user: docker-user

  tasks:
    - name: Install prerequisite Packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add docker APT Repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker Packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Ensure docker service is running and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      user:
        name: "{{ docker_group_user }}"
        groups: docker
        append: yes

