---
# Ansible Playbook: Deploy Filebeat with Security Monitoring
# Configures hosts for authentication, sudo, and command tracking

- name: Deploy Filebeat Security Monitoring Stack
  hosts: monitored_hosts
  become: yes
  vars:
    elasticsearch_host: "100.79.53.58:9200"
    kibana_host: "100.79.53.58:5601"
    filebeat_version: "8.19.8"
    
  tasks:
    # ===== Install Dependencies =====
    - name: Install required packages (Debian/Ubuntu)
      apt:
        name:
          - apt-transport-https
          - wget
          - auditd
          - audispd-plugins
          - gpg
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages (RedHat/Fedora)
      dnf:
        name:
          - wget
          - audit
          - audispd-plugins
        state: present
      when: ansible_os_family == "RedHat"

    # ===== Install Filebeat (Debian/Ubuntu) =====
    - name: Download Elastic GPG key (Debian/Ubuntu)
      get_url:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        dest: /tmp/GPG-KEY-elasticsearch
      when: ansible_os_family == "Debian"

    - name: Add Elastic GPG key (Debian/Ubuntu)
      shell: |
        gpg --dearmor < /tmp/GPG-KEY-elasticsearch > /usr/share/keyrings/elastic-keyring.gpg
      args:
        creates: /usr/share/keyrings/elastic-keyring.gpg
      when: ansible_os_family == "Debian"

    - name: Add Elastic repository (Debian/Ubuntu)
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x
      when: ansible_os_family == "Debian"

    - name: Install Filebeat (Debian/Ubuntu)
      apt:
        name: filebeat
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # ===== Install Filebeat (RedHat/Fedora) =====
    - name: Add Elastic repository (RedHat/Fedora)
      yum_repository:
        name: elastic-8.x
        description: Elastic repository for 8.x packages
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Install Filebeat (RedHat/Fedora)
      dnf:
        name: filebeat
        state: present
      when: ansible_os_family == "RedHat"

    # ===== Configure Auditd Rules =====
    - name: Create audit rules for security monitoring
      copy:
        dest: /etc/audit/rules.d/security-monitoring.rules
        content: |
          # Capture Command Execution
          -a always,exit -F arch=b64 -S execve -k exec
          -a always,exit -F arch=b32 -S execve -k exec
          # Monitor sudo usage
          -w /usr/bin/sudo -p x -k sudo_execution
          -w /etc/sudoers -p wa -k sudoers_changes
          -w /etc/sudoers.d/ -p wa -k sudoers_changes
          
          # Monitor privilege escalation
          -w /bin/su -p x -k su_execution
          
          # Monitor user/group changes
          -w /etc/passwd -p wa -k user_modification
          -w /etc/group -p wa -k group_modification
          -w /etc/shadow -p wa -k shadow_modification
          
          # Monitor authentication
          -w /etc/pam.d/ -p wa -k pam_modification
          
          # Monitor sensitive file access
          -w /etc/ssh/sshd_config -p wa -k sshd_config_change
      notify: restart auditd

    # ===== Configure Filebeat =====
    - name: Configure Filebeat main config
      template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0600'
      notify: restart filebeat

    - name: Enable Filebeat system module
      command: filebeat modules enable system
      args:
        creates: /etc/filebeat/modules.d/system.yml
      notify: restart filebeat

    - name: Enable Filebeat auditd module
      command: filebeat modules enable auditd
      args:
        creates: /etc/filebeat/modules.d/auditd.yml
      notify: restart filebeat

    - name: Configure system module
      copy:
        dest: /etc/filebeat/modules.d/system.yml
        content: |
          - module: system
            syslog:
              enabled: true
              var.paths: ["/var/log/syslog*", "/var/log/messages*"]
            
            auth:
              enabled: true
              var.paths: 
                - "/var/log/auth.log*"
                - "/var/log/secure*"
      notify: restart filebeat

    - name: Configure auditd module
      copy:
        dest: /etc/filebeat/modules.d/auditd.yml
        content: |
          - module: auditd
            log:
              enabled: true
              var.paths: ["/var/log/audit/audit.log*"]
      notify: restart filebeat

    # ===== Start Services =====
    - name: Enable and start auditd
      shell: |
        systemctl unmask audit-rules.service
        systemctl reset-failed auditd
        systemctl start auditd || service auditd start
      ignore_errors: yes

    - name: Enable and start filebeat
      systemd:
        name: filebeat
        enabled: yes
        state: started

    # ===== Verify Setup =====
    - name: Test Filebeat configuration
      command: filebeat test config
      register: config_test
      changed_when: false
      failed_when: config_test.rc != 0

    - name: Test Elasticsearch output
      command: filebeat test output
      register: output_test
      changed_when: false
      failed_when: false  # Don't fail if ES unreachable, just warn
      ignore_errors: yes

    - name: Display connection test results
      debug:
        msg: |
          Config Test: {{ 'PASSED' if config_test.rc == 0 else 'FAILED' }}
          Elasticsearch Test: {{ 'PASSED' if output_test.rc == 0 else 'FAILED - Check connectivity to {{ elasticsearch_host }}' }}

  handlers:
    - name: restart auditd
      shell: |
        /sbin/augenrules --load
        systemctl reset-failed auditd
        systemctl restart auditd || (pkill -9 auditd && systemctl start auditd)
        
    - name: restart filebeat
      systemd:
        name: filebeat
        state: restarted

# ===== Setup Dashboards (runs once from localhost) =====
- name: Setup Elasticsearch index templates and dashboards
  hosts: localhost
  connection: local
  become: yes
  vars:
    elasticsearch_host: "10.0.10.50:9200"
    kibana_host: "10.0.10.50:5601"
  
  tasks:
    - name: Check if any monitored hosts are available
      set_fact:
        first_host: "{{ groups['monitored_hosts'][0] }}"
      when: groups['monitored_hosts'] | length > 0

    - name: Load Filebeat dashboards into Kibana
      command: >
        /usr/bin/filebeat setup --dashboards
        -E setup.kibana.host={{ kibana_host }}
        -E output.elasticsearch.hosts=["{{ elasticsearch_host }}"]
      delegate_to: "{{ first_host }}"
      run_once: true
      when: first_host is defined
      ignore_errors: yes  # Don't fail if dashboards can't load