---

- name: Discover Services On all Servers
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Search login history for suspicious IPs
      shell: last | grep -E "45\.159\.98|45\.159\.97|5\.161\.218"
      register: suspicious_logins
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Search Log History for suspicious IPs
      shell: sudo grep "Accepted password" /var/log/auth.log | grep -E -v "10.0.0|192.168.0"
#      shell: grep "Accepted password" /var/log/auth.log | grep -E "45\.159\.98\.145|45\.159\.97\.233|5\.161\.218\.233|192\.73\.242"
      register: password_accepted
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Search Log History for Accepted Public Key
      shell: sudo grep "Accepted publickey" /var/log/auth.log | grep -E -v "10.0.0|192.168.0"
#      shell: sudo grep "Accepted publickey" /var/log/auth.log  | grep -E "45\.159\.98\.145|45\.159\.97\.233|5\.161\.218\.233|209\.177\.156|199\.38\.162|192\.73\.242|68\.183\.90"
      register: public_key
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Display Results
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "IP: {{ ansible_default_ipv4.address }}"
          - "Susp. Logins:  {{ suspicious_logins.stdout | default('None Found') }}"
          - "Log History-Passwords: {{ password_accepted.stdout }}"
          - "Accepted Public Key: {{ public_key.stdout }}"
