---

- hosts:  all
  become: true
  tasks:

  - name: Update apt index files from repositories
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: web-servers
  become: true
  tasks:

  - name: Install Apache on Web Servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
