---

## Outputs system_health_<date>.log for use with parse_report.py

- name: Daily System Health Report for Python Export
  hosts: all
  become: yes
  gather_facts: yes
  ignore_unreachable: yes
  any_errors_fatal: no

  vars:
    report_dir: /tmp
    report_file: "{{ report_dir }}/daily_report{{ ansible_date_time.date }}.log"

  tasks:
    - name: Ensure report directory exists
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: ansible_hostname is defined and ansible_date_time is defined and ansible_product_uuid is defined

    # --- Disk Usage  ---

    - name: Get Filtered Disk Usage
      ansible.builtin.shell:
        df -h |
        grep -Ev 'tmpfs|udev|/run|/dev/shm|/run/user|overlay'
      register: disk_info
      when: ansible_hostname is defined and ansible_date_time is defined and ansible_product_uuid is defined

    # --- Systemd Service Check ---- 

    - name: Check for Failed Systemd Services
      ansible.builtin.shell: systemctl --failed --no-pager || true
      register: failed_services
      when: ansible_hostname is defined and ansible_date_time is defined and ansible_product_uuid is defined

    # --- Optional Security & SSH Review ---

    - name: Check Recent Failed SSH Logins
      ansible.builtin.shell: journalctl -u ssh -p 4 --since "24 hours ago" --no-pager || true
      register: ssh_failed
      changed_when: false
      when: ansible_hostname is defined and ansible_date_time is defined and ansible_product_uuid is defined

    # --- Detailed Log Checks

    - name: Detailed System Log Output
      ansible.builtin.shell: |
        sudo journalctl --priority 3 --output=verbose --no-pager --since today
      register: critical_logs_today
      changed_when: false
      when: ansible_hostname is defined and ansible_date_time is defined and ansible_product_uuid is defined

    # --- Write to Log File ---

    - name: Create Daily System Report
      ansible.builtin.copy:
        dest: "{{ report_file }}"
        owner: root
        group: root
        mode: '0644'
        content: |


          --- Host: {{ ansible_hostname }}
          --- Date: {{ ansible_date_time.date }}
          --- UUID: {{ ansible_product_uuid }}
          ===BEGIN:STORAGE===
          {{ disk_info.stdout | default('N/A') }}
          ===END:STORAGE===

          ===BEGIN:FAILED_SERVICES===
          {{ failed_services.stdout | default('None detected') }}
          ===END:FAILED_SERVICES===

          ===BEGIN:FAILED_SSH===
          {{ ssh_failed.stdout | default('None') }}
          ===END:FAILED_SSH===

          ===BEGIN:CRITICAL_LOGS_PRIORITY===
          {{ critical_logs_today.stdout | default('No logs 0-3') }}
          ===END:CRITICAL_LOGS_PRIORITY===
      when: ansible_hostname is defined and ansible_date_time is defined and ansible_product_uuid is defined

    # --- Fetch Reports Back to Controller ---

    - name: Ensure Local Directory Exists
      delegate_to: localhost
      run_once: true
      become: false
      ansible.builtin.file:
        path: "/tmp/system_reports"
        state: directory
        mode: '0777'
      when: ansible_date_time is defined

    - name: Fetch Report From Each Host to Controller
      ansible.builtin.fetch:
        src: "{{ report_file }}"
        dest: "/tmp/system_reports/"
        flat: no
      when: ansible_date_time is defined

    # --- Combine all Reports into one File (local only) ---

- name: Combine all fetched reports into one master file
  hosts: localhost
  gather_facts: false
  ignore_unreachable: yes


  vars:
    combined_report_dir: "/tmp/system_reports"
    # Keep combined_report_file here, we will replace the lookup later
    combined_report_file: "{{ combined_report_dir }}/system_health_FIXME.log" # Placeholder
    remote_report_dir: "/home/sm-user/vm_system_reports/"

  tasks:
    # --- STEP 1: Define a consistent local date variable ---
    - name: Set local date fact for file naming and lookup
      ansible.builtin.set_fact:
        local_date: "{{ lookup('pipe', 'date +%F') }}"

    # --- STEP 2: Ensure Combined report directory exists (already done) ---
    - name: Ensure Combined report directory exists
      ansible.builtin.file:
        path: "{{ combined_report_dir }}"
        state: directory

    # --- STEP 3: Merge all individual reports into one file ---
    - name: Merge all individual reports into one file
      ansible.builtin.shell: |
        # Use the consistent local_date fact for file matching
        cat {{ combined_report_dir }}/*/daily_report{{ local_date }}.log >> {{ combined_report_dir }}/system_health_{{  local_date }}.log
        # Remove original individual reports and sub-directories
        find {{ combined_report_dir }} -type f -name "daily_report{{ local_date }}.log" -delete
        find {{ combined_report_dir }} -mindepth 1 -type d -empty -delete
      args:
        executable: /bin/bash
      ignore_errors: yes

    # --- STEP 4: Display the combined report path ---

    - name: Display Combined Report Summary Path
      ansible.builtin.debug:
        msg: "Combined Daily report saved at: {{ combined_report_dir }}/system_health_{{ local_date }}.log"

# --- STEP 5: Copy the final report to remote host ---

- name: Copy combined report to archive server
  hosts: report_archive_servers
  become: true
  gather_facts: false
  ignore_unreachable: yes
  vars:
    local_report: "/tmp/system_reports/system_health_{{ lookup('pipe', 'date +%F') }}.log"
    remote_report_dir: "/home/sm-user/vm_system_reports"

  tasks:
    - name: Ensure remote report directory exists
      ansible.builtin.file:
        path: "{{ remote_report_dir }}"
        state: directory
        owner: sm-user
        group: sm-user
        mode: '0755'

    - name: Copy combined report from localhost to archive host
      ansible.builtin.copy:
        src: "{{ local_report }}"
        dest: "{{ remote_report_dir }}/vm_system_report_{{ lookup('pipe', 'date +%F') }}.log"
        owner: sm-user
        group: sm-user
        mode: '0770'
