---

- name: Daily System Health Report for Python Export
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    report_dir: .
    report_file: "{{ report_dir }}/daily_report{{ ansible_date_time.date }}.log"

  tasks:
    - name: Ensure report directory exists
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    # --- Disk Usage  ---

    - name: Get Filtered Disk Usage
      ansible.builtin.shell:
        df -h |
        grep -Ev 'tmpfs|udev|/run|/dev/shm|/run/user|overlay'
      register: disk_info

    # --- Systemd Service Check ---- 

    - name: Check for Failed Systemd Services
      ansible.builtin.shell: systemctl --failed --no-pager || true
      register: failed_services

    # --- Log Checks ---

    - name: Get High-Priority Logs (errors and criticals)
      ansible.builtin.command: journalctl -p 3 -xb --no-pager
      register: log_critical
      changed_when: false

    # --- Optional Security & SSH Review ---

    - name: Check Recent Failed SSH Logins
      ansible.builtin.shell: journalctl -u ssh -p 4 --since "24 hours ago" --no-pager || true
      register: ssh_failed
      changed_when: false

    # --- Write to Log File ---

    - name: Create Daily System Report
      ansible.builtin.copy:
        dest: "{{ report_file }}"
        owner: root
        group: root
        mode: '0644'
        content: |
          --- Host: {{ ansible_hostname }}
          --- Date: {{ ansible_date_time.date }}
          --- UUID: {{ ansible_product_uuid }}
          {{ disk_info.stdout | default('N/A') }}


          --- FAILED SERVICES ---
          {{ failed_services.stdout | default('None detected') }}

          {% set log_content = log_critical.stdout | default('-- No entries --') | trim %}
          --- CRITICAL LOGS (journalctl -p 3) ---
          {% if log_content != '-- No entries --' %}
          {{ log_content }}
          {% else %}
          {{ log_content }}
          {% endif %}

          --- PENDING UPDATES ---
          {% if ansible_os_family == 'Debian' %}
          {{ apt_updates.stdout | default('No pending updates') }}
          {% elif ansible_os_family == 'RedHat' %}
          {{ dnf_updates.stdout | default('No pending updates') }}
          {% else %}
          No update info available for {{ ansible_os_family }}
          {% endif %}
          --- RECENT FAILED SSH LOGINS ---
          {{ ssh_failed.stdout | default('None') }}


    # --- Fetch Reports Back to Controller ---

    - name: Ensure Local Directory Exists
      delegate_to: localhost
      run_once: true
      become: false
      ansible.builtin.file:
        path: "./system_reports"
        state: directory
        mode: '0755'

    - name: Fetch Report From Each Host to Controller
      ansible.builtin.fetch:
        src: "{{ report_file }}"
        dest: "./system_reports/"
        flat: no

    # --- Combine all Reports into one File (local only) ---

- name: Combine all fetched reports into one master file
  hosts: localhost
  gather_facts: false
  vars:
    combined_report_dir: "./system_reports"
    # Keep combined_report_file here, we will replace the lookup later
    combined_report_file: "{{ combined_report_dir }}/system_health_FIXME.log" # Placeholder

  tasks:
    # --- STEP 1: Define a consistent local date variable ---
    - name: Set local date fact for file naming and lookup
      ansible.builtin.set_fact:
        local_date: "{{ lookup('pipe', 'date +%F') }}"

    # --- STEP 2: Ensure Combined report directory exists (already done) ---
    - name: Ensure Combined report directory exists
      ansible.builtin.file:
        path: "{{ combined_report_dir }}"
        state: directory

    # --- STEP 3: Merge all individual reports into one file ---
    - name: Merge all individual reports into one file
      ansible.builtin.shell: |
        # Use the consistent local_date fact for file matching
        cat {{ combined_report_dir }}/*/daily_report{{ local_date }}.log >> {{ combined_report_dir }}/system_health{{  local_date }}.log
        # Remove original individual reports and sub-directories
        find {{ combined_report_dir }} -type f -name "daily_report{{ local_date }}.log" -delete
        find {{ combined_report_dir }} -mindepth 1 -type d -empty -delete
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Display Combined Report Summary Path
      ansible.builtin.debug:
        msg: "Combined Daily report saved at: {{ combined_report_dir }}/system_health{{ local_date }}.log"

#    - name: Copy Combined Report to system_reports
#      copy:
#        src: "{{ combined_report_dir }}/system_health_{{ local_date }}.log"
#        dest: "web_log/html/daily_logs/system_health_{{ local_date }}.log"

